### ISSUE TITLE
Crush script in Blnder 4.1

### ISSUE THREAD

**Issue by MikhaylyukDO** [A-Ribeiro/CustomBlenderFBXExporter#7]
Crush script in Windows 11  Blnder 4.1 

Python: Traceback (most recent call last):
  File "C:\Users\Rassel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_fbx_custom\__init__.py", line 663, in execute
    return export_fbx_bin.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rassel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_fbx_custom\export_fbx_bin.py", line 3536, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rassel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_fbx_custom\export_fbx_bin.py", line 3419, in save_single
    fbx_objects_elements(root, scene_data)
  File "C:\Users\Rassel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_fbx_custom\export_fbx_bin.py", line 3216, in fbx_objects_elements
    fbx_data_mesh_elements(objects, me_obj, scene_data, done_meshes)
  File "C:\Users\Rassel\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_fbx_custom\export_fbx_bin.py", line 1145, in fbx_data_mesh_elements
    me.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

**Comment by A-Ribeiro** [comment]
Fixed in tag 1.13

Release url:
 https://github.com/A-Ribeiro/CustomBlenderFBXExporter/releases/tag/v1.13
